# 9.异常

## 一、单选

- 题目说明：Java语言中异常的分类是哪项？（）

  A.运行时异常和异常 

  B. 必检异常和非必检异常 

  C.错误和异常

  D.错误和运行时异常

​       题目难度：简单

​       题目考核知识点：异常

​       答案：B

​       题目解析：异常分类可分为必检异常和非必检异常（运行时异常）或编译错误和运行错误



- 题目说明：所有异常的父类是哪项？（）

  A. Throwable

  B.  Error

  C.  RuntimeException

  D.  Exception

​       题目难度：简单

​       题目考核知识点：异常

​       答案： A

​       题目解析：所有异常类都是继承自Throwable类。



- 题目说明：下列属于非必检异常的是哪项？（）

  A.  SQLException

  B.   IOException

  C.   NullPointerException

  D.   ClassNotFoundException

​       题目难度： 简单

​       题目考核知识点：异常

​       答案：C

​       题目解析：非必检异常在默认情况下会得到自动处理。不检查异常是指对Error类或其子类对象和RuntimeException类或其子类就不用捕获或抛出。



- 题目说明：在方法的声明中，要求该方法必须抛出异常时使用哪个关键字？（）

  A.throw

  B. catch

  C.finally

  D.throws

​       题目难度：简单

​       题目考核知识点：异常

​       答案：D

​       题目解析：throws声明异常。使用throws声明的方法表示此方法被调用时，一旦产生了异常就立即将异常对象传递出去，交由调用处进行处理。



- 题目说明：现有：

     class Birds{  

  ​		public static void main(String [ ] args) {

  ​				try { 

  ​						 throw new Exception () ; 

  ​					} catch (Exception e) {  

  ​             				 	try { 

  ​								throw new Exception () ; 

  ​        						 } catch (Exception e2) {  

  ​		    						System.out.print("inner"); 

  ​							}

  ​				 		System. out.print ( "middle" ) ; 

  ​					}

  ​			 System.out.print ("outer") ;

  ​		}

  ​	}

  结果是什么？（）

  A.inner outer

  B.  middle outer

  C.inner middle outer 

  D.编译失败 

​       题目难度：简单

​       题目考核知识点：异常

​       答案：C

​       题目解析：使用throw抛出异常。



- 题目说明：在异常处理中，若要释放资源、关闭文件等由（）来完成？

  A.try子句

  B. catch子句

  C.finally子句

  D.throw子句

​       题目难度：简单

​       题目考核知识点：异常

​       答案：C

​       题目解析：finally代码块通常用于关闭资源。



- 题目说明：以下关于异常的代码的执行结果是（）？

    public  class Test{  

  ​		public static void main(String [] args) {

  ​				try { 

  ​						System.out.print("try");

  ​						return;

  ​					} catch (Exception e) {  

  ​             				 	 System.out.print ("catch");  

  ​        				 } finally { 

  ​		    				System.out.print("finally"); 

  ​					}

  ​		}

  ​	}

  A.try  catch  finally

  B.   catch  finally  try

  C. try  finally

  D.try

​       题目难度：简单

​       题目考核知识点：异常

​       答案：C

​       题目解析：不论try语句块内发生了哪种异常，也不管try和catch语句块是否可以正常执行，finally代码块都会保证被执行。在此题中，打印了try后，并无异常，不会执行catch语句，但执行到return语句，此时要先执行finally，最后在return。



- 题目说明：以下关于异常的代码的执行结果是（）？

    public  class Test2{  

  ​		public static void main(String [] args) {

  ​				try { 

  ​						int i=1;

  ​						System.out.print(i++);

  ​        				 } finally { 

  ​		    				System.out.print(++i); 

  ​					}

  ​		}

  ​	}

  A.  1   2

  B.  1   1

  C. 编译错误

  D.  1

​       题目难度：难

​       题目考核知识点：异常

​       答案：C

​       题目解析：变量i只在try语句块内定义，其有效范围仅在try语句块内。



- 题目说明：以下关于异常的代码的执行结果是（）？

    public  class Test3{  

  ​		public static void main(String [] args) {

  ​			int  n=fun(2);

  ​			System.out.print(n);

  ​		}

  ​		public static int fun(int i){

  ​			try { 

  ​						int m=i/0;

  ​						return i++;

  ​					} catch (ArithmeticException e) {  

  ​             				 	return (i+3);  

  ​        				 } finally { 

  ​		    				return (i+8);

  ​					}

  ​		}		

  ​	}

  A. 2

  B.  5

  C. 10

  D.编译错误

​       题目难度：简单

​       题目考核知识点：异常

​       答案：C

​       题目解析：在执行try或catch语句块中的return语句时，若有finally语句块，会先执行finally语句块。所以会先执行finally中的return 语句，返回10并退出方法。

## 二、多选

- 题目说明：关于try...catch...finally结构，描述正确的是哪项？ （）

  A.  可以有多个catch 

  B. 只能有一个catch 

  C.可以没有catch

  D.finally必须有 

​       题目难度：简单

​       题目考核知识点：异常

​       答案：AC

​       题目解析：try语句不能单独存在，其后至少要有一个catch或finally语句块。



- 题目说明：自定义异常类时，可以继承的类是（     ） 

  A.Error

  B. Applet

  C.Exception

  D.Exception的子类

​       题目难度：中等

​       题目考核知识点：异常

​       答案：CD

​       题目解析：自定义的异常类至少应继承Throwable类，一般让其继承Exception或Exception的子类来创建自定义的异常类。



- 题目说明：现有：

     class Calc{  

  ​		public static void main(String [] args) {

  ​				try { 

  ​						int x = Integer.parselnt ("42a") ;

  ​						 //insert code here 

  ​						System.out.print ("oops"); 

  ​					} 

  ​		}

  ​	}

  下面哪两行分别插入到第五行，会导致输 "oops" ? （）

  A. } catch (IllegalArgumentException e) {

  B.  } catch (IllegalStateException c) { 

  C. } catch (NumbelFormatException n) {

  D. } catch (ClassCastException c) {  

​       题目难度：中等

​       题目考核知识点：异常

​       答案：AC

​       题目解析：IllegalArgumentException表示传入非法参数异常；NumbelFormatException 表示数字格式异常。IllegalStateException：java环境或java应用程序状态异常；ClassCastException对象转换异常。



- 题目说明：现有

  class Flow{  

  ​	public static void main(String [] args) {

  ​				try { 

  ​						System.out.print ("before") ;

  ​						 doRiskyThing ( ) ; 

  ​						System.out.print ("after"); 

  ​					}  catch (Exception e) { 

  ​						 System.out.print ("catch") ; 

  ​					}

  ​				 System. out .println ( " done") ; 

  ​	}

   	public static void doRiskyThing() throws Exception{ 

   		// this code returns unless it throws an Exception 

  ​	}

  }

   可能会产生哪两项结果 ?（）

  A.before catch 

  B.  before after done 

  C.before catch done 

  D. before after catch 

​       题目难度：简单

​       题目考核知识点：异常

​       答案：BC

​       题目解析：1>先打印了before,之后调doRiskyThing()方法,这时并无异常，接着打印after,最后打印done。

​                       2>先打印了before,之后调doRiskyThing()方法,这时有异常抛出，所以打印catch,最后打印done。

## 三、填空 

### 程序填空





### 读程序写结果







## 四、简答

### 基本概念解释

- 题目说明：Java异常处理中，关键字try、catch、finally、throw、throws分别代表什么含义？ 

​       题目难度：难

​       题目考核知识点：异常

​       答案：在try中写可能抛出异常的语句；catch中是对该类型的异常进行处理；finally为确保一段代码不管发生什么异常都被执行一段代码，通常用于释放资源； throw语句用来明确地抛出一个异常； throws用来声明一个成员函数可能抛出的各种异常。

​       题目解析：略



- 题目说明：.如何自定义异常类？  

​       题目难度：简单

​       题目考核知识点：异常

​       答案：class  自定义的异常类名称 extends Exception或Exception的子类{} 

​       题目解析：略



- 题目说明：什么是RuntimeException？列举至少4个RuntimeException的子类  ？ 

​       题目难度：难

​       题目考核知识点：异常

​       答案：RuntimeException是java中所有运行时异常的父类，不需要用throws 声明抛出 异常对象所属类，也可以不用throw 抛出异常对象或异常引用。举例：ClassCastException 、ArithmeticException 、NullPointerException 、IndexOutOfBoundsException 、ArrayIndexOutOfBoundsException

​       题目解析：略



- 题目说明：throws和throw的区别 ？ 

​       题目难度：难

​       题目考核知识点：异常

​       答案：1、throws出现在方法函数头；而throw出现在函数体。throw是语句抛出一个异常，一般是在代码块的内部，当程序出现某种逻辑错误时由程序员主动抛出某种特定类型的异常。程序在执行到throw语句时立即停止，它后面的语句都不执行；throws关键字通常被应用在声明方法时，用来指定可能抛出的异常，多个异常可以使用逗号隔开。当在主函数中调用该方法时，如果发生异常，就会将异常抛给指定异常对象。

 2、throws是方法可能抛出异常的声明，throws表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某种异常对象。 

3、通过throw抛出异常后，如果想在上一级代码中来捕获并处理异常，则需要在抛出异常的方法中使用throws关键字在方法声明中指明要跑出的异常；如果要捕捉throw抛出的异常，则必须使用try—catch语句。

​       题目解析：略





### 程序题改错

- ​题目说明： 下列代码段中试图用try-catch-catch结构捕获和处理异常，其中有的地方是错误的，请将错误的地方纠正过来。

  int m，n;

  int[] a=new int[5];

  n=10;

  m=10;

  try{	

  ​	m=int.Parse(“2000$”);

  ​	for(int i=0; i<=a.Length; i++)	 

  ​		 a[i]=i;  

	catch(Exception e1){	

  ​	System.out.println("产生异常："+e1); 	

  }catch(IndexOutOfRangeException e2){

  ​	System.out.println("产生异常："+e2);	}

​       题目难度：简单

​       题目考核知识点：异常

​       答案：将两个catch块的位置对调一下。

​	题目解析：异常类放的位置 一般是将最细化的异常类放在最前面，之后载使用父异常类。



- ​题目说明： 下列代码段中其中有的地方是错误的，请将错误的地方纠正过来。

  class UserException implements Exception{

  ​       	String info;

  ​	public  UserException(String info){

  ​		this.info=info;	

  ​	}

  ​	public void callException() throw UserException{

  ​		throw UserException("callException");

  ​	}

  ​	public static void main(String[] args){

  ​		try{

  ​			UserException ue=new UserException("");

  ​			ue.callException();

  ​		}catch(UserException e){

  ​			System.out.println("产生异常:"+e.info);

  ​		}final{

  ​		System.out.println("释放资源");

  ​		}

  ​	}

  ​}

​       题目难度：简单

​       题目考核知识点：异常

​       答案：implements改成extends；public void callException() throw UserException 改为public void callException() throws UserException 

​		throw UserException("callException")改成throw new UserException("callException");

​		final改成finally

​	题目解析：Exception是一个类，自定义的异常类继承Exception，而不是实现。用在方法头部的是throws，用来声明异常。使用throw抛出异常时，抛出的是异常的实例。应该是finally语句块，而final是 可以用来修饰常量、方法、类。

## 五、编程题

- ​题目说明： 

​       题目难度：

​       题目考核知识点：异常

​       答案：

```java
  
```

​    题目解析：
